### ISSUE TITLE
Autofac None of the constructors found

### ISSUE THREAD

**Issue by vittrup88** [ivanpaulovich/clean-architecture-webapi-ef-core#1]
First of all thanks alot for a nice clean design template for creating a web api.
I have made some changes because some of the projects reference .Netstandard ?
I have got the solution up and running and have changed from sqlserver to postgresql and it migrates well.

I tried making my own usecase called tilesets and i have followed the princip from Consumer and Register usecase. I have a controller but when i call my post I get the following error :

`
An unhandled exception occurred while processing the request.
DependencyResolutionException: None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'MyWallet.Application.UseCases.Tilesets.TilesetUseCase' can be invoked with the available services and parameters:
Cannot resolve parameter 'MyWallet.Application.Repositories.ITilesetWriteOnlyRepository tilesetWriteOnlyRepository' of constructor 'Void .ctor(MyWallet.Application.Repositories.ITilesetWriteOnlyRepository)'.
`

I cannot figure what is going wrong else that autofac has no registration of ITilesetWriteOnlyRepository ?
I have tried googling but cannot see any solutions since every other seems to impliment as services one by one, but maybe you can give me a hint ?

My usecase is like this:
`namespace MyWallet.Application.UseCases.Tilesets
{
    using System.Threading.Tasks;
    using MyWallet.Domain.Tilesets;
    using MyWallet.Application.Repositories;
    using MyWallet.Domain.ValueObjects;

    public sealed class TilesetUseCase : ITilesetUseCase
    {
        private readonly ITilesetWriteOnlyRepository _tilesetWriteOnlyRepository;
        
        public TilesetUseCase(
            ITilesetWriteOnlyRepository tilesetWriteOnlyRepository
           )
        {
            _tilesetWriteOnlyRepository = tilesetWriteOnlyRepository;
        }

        public async Task<TilesetOutput> Execute(Name name)
        {
            Tileset tileset = new Tileset(name);

            await _tilesetWriteOnlyRepository.Add(tileset);

            TilesetOutput output = new TilesetOutput(tileset);
            return output;
        }
    }
}

`
    namespace MyWallet.Application.Repositories {
        using System.Threading.Tasks;
        using MyWallet.Domain.Tilesets;

        public interface ITilesetWriteOnlyRepository {
            Task Add (Tileset tileset);
            Task Update (Tileset tileset);
        }
    }
`

Any suggestions ?

**Comment by vittrup88** [comment]
Somehow this issue got solved by a fresh reboot without any changes

**Comment by ivanpaulovich** [comment]
Hi Anders,
Nice to hear that!
Without going deep into details. That error is about a missing registration for the implementation of ITilesetWriteOnlyRepository.

My proposed solution uses Autofac modules setted to look for Interfaces and Implementation by convention. Make sure you are loading the correct module at application startup then if the rules on that module are correct.

If you are not familiar with autofac you can change it to another DI framework you like :)

Feel free to reach me in case of questions.
