### ISSUE TITLE
Question: How to update data to multiple EF Core Repositories in one unit of work?

### ISSUE THREAD

**Issue by linhub15** [ivanpaulovich/clean-architecture-webapi-ef-core#2]
If adding the account fails (line 29), will it rollback adding the customer (line 28)?

https://github.com/ivanpaulovich/clean-architecture-webapi-ef-core/blob/6d3ac936bb87a94cc926a9730e93082d2ba5acee/source/MyWallet.Application/UseCases/Register/RegisterUseCase.cs#L28-L29

My understanding is that when calling `SaveChanges()` it ends the EF Unit of work.
Since the implementation of `IAccountWriteOnlyRepository.Add()` and `ICustomerWriteOnlyRepository.Add()` call `_context.SaveChangesAsync()` they are independent transactions.

This may cause data inconsistencies since customers will be added but the account will fail.

Is there a way to implement the clean architecture while preserving the Unit of work, transaction nature of EF Core?

**Comment by ivanpaulovich** [comment]
Hey @linhub15,

I kept the UnitOfWork outside of this project, maybe I should revisit it.
What do you need to achieve this is:

[Unit Of Work interface](https://github.com/ivanpaulovich/clean-architecture-manga/blob/master/src/Application/Services/IUnitOfWork.cs)

[Unit of Work implementation](https://github.com/ivanpaulovich/clean-architecture-manga/blob/master/src/Infrastructure/EntityFrameworkDataAccess/UnitOfWork.cs)

[Dependency Injection Setup](https://github.com/ivanpaulovich/clean-architecture-manga/blob/master/src/WebApi/DependencyInjection/SQLServerInfrastructureExtensions.cs)

[Revisit the Repositories to avoid SaveChanges()](https://github.com/ivanpaulovich/clean-architecture-manga/blob/master/src/Infrastructure/EntityFrameworkDataAccess/Repositories/CustomerRepository.cs)

All this links are from Clean Architecture Manga project, please check out for inspiration.

**Comment by linhub15** [comment]
Nice! I like how you use the `IDisposable` for `IUnitOfWork`. If we put the `_context.SaveChangesAsync()` in the `Dispose` method, can we wrap the unit of work in a `using` block? 

```
// RegisterUseCase.cs
... // unit of work injected

using (_unitOfWork) 
{
    await _customerWriteOnlyRepository.Add (customer); 
    await _accountWriteOnlyRepository.Add (account, credit);
} 
```

Would it automatically call save changes at the end of the block, or is it better to be explicit and call `_unitOfWork.SaveChangesAsync()` at the end like the Clean Architecture Manga project examples.

**Comment by ivanpaulovich** [comment]
When we use `AddScoped` the object is automatically disposed at the end of request. No need to wrap the repositories with `using` :)

**Comment by ivanpaulovich** [comment]
Now I got what you are saying. I can try adding the `SaveChangesAsync` in the Dispose method, it  should work but needs some investigation

**Comment by linhub15** [comment]
On second thought saving the dB context in dispose could have many unknown side effects. The dB context could be disposed in multiple ways. Maybe it's better to be explicit.

**Comment by smariano88** [comment]
I wouldn't call SaveChanges on dispose. 
Using statements are translated by the compiler to something like:
```
try{
    await _customerWriteOnlyRepository.Add (customer); 
    await _accountWriteOnlyRepository.Add (account, credit);
} 
catch {
}
finally{
    _unitOfWork.Dispose();
}
```
So if you get an exception on _accountWriteOnlyRepository.Add, by calling SaveChanges on the Dispose method, you would end up with the customer saved on your database. 

Reference: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-statement
