### ISSUE TITLE
Where do I tell the application to choose between InMemory persistence or EF persistence? EF Definiciones de ef- Prefijo 1 assimilated before f (as in efface , effloresce ).

### ISSUE THREAD

**Issue by hackbray** [ivanpaulovich/clean-architecture-webapi-ef-core#3]

**Comment by ivanpaulovich** [comment]
Hey @hackbray,

The WebApi uses Autofac DI and it loads for `ASPNETCORE_ENVIRONMENT=Development` the inMemory data access and for `ASPNETCORE_ENVIRONMENT=Production` the Entity Framework.

To run on top of a InMemory persistance layer:

```
dotnet run --environment="dev" --project source/MyWallet.WebApi/MyWallet.WebApi.csproj
```

To run on top of a SQL Server persistance layer you need to setup the SQL Server database in steps ahead then run:

```
dotnet run --environment="production" --project source/MyWallet.WebApi/MyWallet.WebApi.csproj
```

The relevant code that do the trick are:

https://github.com/ivanpaulovich/clean-architecture-webapi-ef-core/blob/master/source/MyWallet.WebApi/Startup.cs#L40

Loads the InMemory module:
https://github.com/ivanpaulovich/clean-architecture-webapi-ef-core/blob/master/source/MyWallet.WebApi/autofac.json

Loads the SQL Server module:
https://github.com/ivanpaulovich/clean-architecture-webapi-ef-core/blob/master/source/MyWallet.WebApi/autofac.production.json

**Comment by hackbray** [comment]
> Hey @hackbray,
> 
> The WebApi uses Autofac DI and it loads for `ASPNETCORE_ENVIRONMENT=Development` the inMemory data access and for `ASPNETCORE_ENVIRONMENT=Production` the Entity Framework.
> 
> To run on top of a InMemory persistance layer:
> 
> ```
> dotnet run --environment="dev" --project source/MyWallet.WebApi/MyWallet.WebApi.csproj
> ```
> 
> To run on top of a SQL Server persistance layer you need to setup the SQL Server database in steps ahead then run:
> 
> ```
> dotnet run --environment="production" --project source/MyWallet.WebApi/MyWallet.WebApi.csproj
> ```
> 
> The relevant code that do the trick are:
> 
> https://github.com/ivanpaulovich/clean-architecture-webapi-ef-core/blob/master/source/MyWallet.WebApi/Startup.cs#L40
> 
> Loads the InMemory module:
> https://github.com/ivanpaulovich/clean-architecture-webapi-ef-core/blob/master/source/MyWallet.WebApi/autofac.json
> 
> Loads the SQL Server module:
> https://github.com/ivanpaulovich/clean-architecture-webapi-ef-core/blob/master/source/MyWallet.WebApi/autofac.production.json

** Thanks for the reply, however I still don't understand the following:

Where you choose to load autofac.json or autofac.production.json for the application to decide where to persist. **

**Comment by ivanpaulovich** [comment]
Hey @hackbray,

Could you check if this line clarify the switch between dev and production?

https://github.com/ivanpaulovich/clean-architecture-webapi-ef-core/blob/6d3ac936bb87a94cc926a9730e93082d2ba5acee/source/MyWallet.WebApi/Program.cs#L22

**Comment by hackbray** [comment]
> Hey @hackbray,
> 
> Could you check if this line clarify the switch between dev and production?
> 
> https://github.com/ivanpaulovich/clean-architecture-webapi-ef-core/blob/6d3ac936bb87a94cc926a9730e93082d2ba5acee/source/MyWallet.WebApi/Program.cs#L22

Hello :), precisely that is my biggest doubt, you have two autofac files: autofac.json and autofac.production.json, in the configuration you add both and place the production one as optional = true, then what will happen when Enviroment be develop, you will not find any files, neither the autofac.json nor the autofac.production.json. So I do not understand how you say which of the two you are going to inject or where I tell my app to choose one of the two.
