### ISSUE TITLE
Unit Of Work implementation page not working

### ISSUE THREAD

**Issue by naeemr** [ivanpaulovich/clean-architecture-webapi-ef-core#4]
Hi ivanpaulovich,

The Unit of Work implementation link is not working

https://github.com/ivanpaulovich/clean-architecture-manga/blob/master/src/Infrastructure/EntityFrameworkDataAccess/UnitOfWork.cs

Please suggest.

**Comment by ivanpaulovich** [comment]
Hi @naeemr,

This file was moved to https://github.com/ivanpaulovich/clean-architecture-manga/blob/master/src/Infrastructure/DataAccess/UnitOfWork.cs

:)

**Comment by naeemr** [comment]
Thank you!
